### ISSUE TITLE
Something about Input and output

### ISSUE THREAD

**Issue by tengwang0318** [csebuetnlp/CrossSum#1]
Hello, I have read your paper 4 times, awesome works! 
I got confused about the input and output. If we want to summarize an article that uses English, into French and Chinese.  Can we use the same model to do that? Or Train two models, one is English-French, another is English-Chinese?

**Comment by Tahmid04** [comment]
Hi, thanks for appreciating our work. The many-to-many model should support any input language and any output language, you do not need multiple models.

**Comment by tengwang0318** [comment]
> Hi, thanks for appreciating our work. The many-to-many model should support any input language and any output language, you do not need multiple models.

I know, but how does the many-to-many model know that which language of model it should output?

**Comment by tengwang0318** [comment]
Does many-to-many model and one-to-many model output summaries in all languages, where we set the range of languages when training the model.

**Comment by Tahmid04** [comment]
The decoder has language-specific BOS tokens. During inference, to indicate which language it should output, the desired BOS tokens are set. The evaluator script has a requires_tgt_lang argument. You may use that to set the output language.

**Comment by tengwang0318** [comment]
Got it, thank you for your relpy. Have a good day!
