### ISSUE TITLE
Finetuning on HF using Seq2SeqTrainer.

### ISSUE THREAD

**Issue by varadhbhatnagar** [csebuetnlp/CrossSum#2]
I need to finetune `csebuetnlp/mT5_m2m_crossSum` using the `Seq2SeqTrainer` on HuggingFace.  What special symbols need to be inserted during tokenization of input-output pairs?

**Comment by abhik1505040** [comment]
Hi, We use language-specific `bos` tokens only for the decoder. The language-to-bos-token mapping is present in the model `config`. Please have a look at the code snippet given on the [model page](https://huggingface.co/csebuetnlp/mT5_m2m_crossSum) to see how you can access it. If you want to readily use our scripts to further fine-tune this model on your own data, just replace `google/mt5-base` with `csebuetnlp/mT5_m2m_crossSum` on this [line](https://github.com/csebuetnlp/CrossSum/blob/main/seq2seq/trainer.sh#L80)
