### ISSUE TITLE
Flan-t5 for training?

### ISSUE THREAD

**Issue by mirfan899** [csebuetnlp/CrossSum#5]
Does CrossSum support Flan-t5 for summarization???

**Comment by abhik1505040** [comment]
Yes, you can finetune any model from the T5 family using our pipeline. You just need to put the appropriate model name in the following block 

https://github.com/csebuetnlp/CrossSum/blob/e798fea7fdb39fa57487ca2cd784f2f9acc004d8/seq2seq/trainer.sh#L92-L93

Please feel free to reopen this issue if you have any further questions.
